update build file to correct deploy error: Error: missing server host

diff --git a/.github/workflows/build-deploy.yaml b/.github/workflows/build-deploy.yaml
--- a/.github/workflows/build-deploy.yaml
+++ b/.github/workflows/build-deploy.yaml
@@ -61,7 +61,23 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION  }} 
-          
+
+      - name: Get Public IP and SHA
+        run: |
+          # Retrieves the EC2 instance's public IP and sets the SHA
+          EC2_PUBLIC_IP=$(aws ec2 describe-instances \
+            --filters "Name=tag:Name,Values=${{ env.AWS_EC2 }}" \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --output text)
+
+          if [ -z "$EC2_PUBLIC_IP" ]; then
+            echo "Error: EC2 Public IP not found"
+            exit 1
+          fi
+
+          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> "$GITHUB_ENV"
+          echo "SHA: $GITHUB_SHA" # Output SHA for debugging and verification
+
       - name: Get Public IP and SHA
         run: |
           # Retrieves the EC2 instance's public IP and sets the SHA
